### PR TITLE
Get auth user instead of hard coding django auth.User

### PR DESCRIPTION
**Pull request by brandoshmando**

### CODE REVIEW

**Comment by brandoshmando** [comment]
- [x] Visit https://dev-ambassador-api.herokuapp.com/consulate
- [x] Confirm that the page loads
- [x] Log in with google
- [x] Confirm that it is successful

For reference, [`get_user_model`](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-contrib-auth) made our lives super easy here, score another for django 1.11...

**Comment by brandoshmando** [comment]
### Deploy Plan
- [ ] Merge this patch into GA repo
- [ ] Deploy ambassador-api master via heroku dashboard

**Comment by brandoshmando** [comment]
@mkuchen please review

**Comment by mkuchen** [comment]
Reviewing

**Review by mkuchen — APPROVED** [review]
:fire:

**Pull request merged**
